FROM python:3.9-slim

# Install dependencies
COPY requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r /app/requirements.txt

# Copy server files
COPY app.py /app/app.py
COPY encryption /app/encryption

WORKDIR /app
CMD ["python3", "app.py"]
